name: autopin self-test
on: push
permissions:
  contents: read
jobs:
  autopin:
    runs-on: ubuntu-latest
    steps:
    - uses: fproulx-boostsecurity/autopin@main
    - uses: chainguard-dev/digestabot@v1
    
